export default {
  itemCamera: [
    {
      _id: "1",
      name: "camera1",
      image: "/image/cam.jpeg",
      price: 1200,
      brand: "HikVision",
      availibity: "Out of Stock",
    },
    {
      _id: "2",
      name: "camera2",
      image: "/image/cam.jpeg",
      price: 150,
      brand: "HikVision",
      availibity: "Out of Stock",
    },
    {
      _id: "3",
      name: "camera3",
      image: "/image/cam.jpeg",
      price: 180,
      brand: "HikVision",
      availibity: "Out of Stock",
    },
    {
      _id: "4",
      name: "camera4",
      image: "/image/cam.jpeg",
      price: 200,
      brand: "HikVision",
      availibity: "Out of Stock",
    },
  ],
  itemDVR: [
    {
      _id: "100",
      name: "DVR1",
      image: "/image/DVR.jpg",
      price: 120,
      brand: "HikVision",
      availibity: "Out of Stock",
    },
    {
      _id: "101",
      name: "DVR2",
      image: "/image/DVR.jpg",
      price: 150,
      brand: "HikVision",
      availibity: "Out of Stock",
    },
    {
      _id: "102",
      name: "DVR3",
      image: "/image/DVR.jpg",
      price: 180,
      brand: "HikVision",
      availibity: "Out of Stock",
    },
    {
      _id: "103",
      name: "DVR4",
      image: "/image/DVR.jpg",
      price: 200,
      brand: "HikVision",
      availibity: "Out of Stock",
    },
  ],
};
